# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test
      run: |
        pushd cherrynas
        chmod +x ./scripts/run_test.sh
        echo "------------------------------"
        echo "Run test"
        echo "------------------------------"
        ./scripts/run_test.sh
        popd
    - name: Run pylint
      run: |
        pushd cherrynas
        pip install pylint
        chmod +x ./scripts/run_pylint.sh
        echo "------------------------------"
        echo "Run pylint"
        echo "------------------------------"
        ./scripts/run_pylint.sh
        popd
    - name: Version up
      run: |
        pushd cherrynas
        chmod +x ./scripts/version_up.sh
        echo "------------------------------"
        echo "Version up"
        echo "------------------------------"
        echo "./scripts/version_up.sh"
        popd
    - name: Build
      run: |
        python setup.py sdist
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: cherrynas
        path: dist
        retention-days: 5
