# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r cnas/requirements.txt
    - name: Run test
      run: |
        pushd cnas
        echo "------------------------------"
        echo "Run test"
        echo "------------------------------"
        ./doc_test.py
        popd
    - name: Run pylint
      run: |
        pushd cnas
        echo "------------------------------"
        echo "Run pylint"
        echo "------------------------------"
        ./pylint_test.py
        popd
    - name: Version up
      run: |
        pushd cnas
        echo "------------------------------"
        echo "Version up"
        echo "------------------------------"
        git config --global user.email "fnwinter@gmail.com"
        git config --global user.name "Action"
        ./version_up.py
        popd
    - name: Build
      run: |
        echo "------------------------------"
        echo "Setup"
        echo "------------------------------"
        python setup.py sdist
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: cherrynas
        path: dist
        retention-days: 5
